### ISSUE TITLE
cannot compile lmbspecialops

### ISSUE THREAD

**Issue by KunB-Fighting** [lmb-freiburg/deeptam#13]
when I compile lmbspecialops, there is always an error occurs
`decode_flo_op.cc:65:15: error: ‘const class tensorflow::StringPiece’ has no member named ‘starts_with’
     if (!data.starts_with("PIEH")) {`
I try to trace back, and found that there is a 'starts_with' function in namespace protobuf/google but not in namespace tensorflow.
how to fix it?

**Comment by benjaminum** [comment]
Downgrading Tensorflow to 1.4 should fix this problem.
If you cannot downgrade have a look at the master branch of lmbspecialops. There this problems is fixed.

**Comment by KunB-Fighting** [comment]
Thaks for the solution, it dose work!
