### ISSUE TITLE
op_kernel.h: no such file or directory

### ISSUE THREAD

**Issue by MrMinemeet** [lmb-freiburg/deeptam#14]
Hi,

I'm failing on running the `make` command after cloning.
This is the error I get:
```
[ 34%] Building NVCC (Device) object lib/CMakeFiles/lmbspecialops.dir/lmbspecialops_generated_warp2d_cuda.cu.o
/home/user/src/DeepTAM/lmbspecialops/src/warp2d_cuda.cu:20:10: fatal error: tensorflow/core/framework/op_kernel.h: No such file or directory
 #include "tensorflow/core/framework/op_kernel.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at lmbspecialops_generated_warp2d_cuda.cu.o.Release.cmake:219 (message):
  Error generating
  /home/user/src/DeepTAM/lmbspecialops/build/lib/CMakeFiles/lmbspecialops.dir//./lmbspecialops_generated_warp2d_cuda.cu.o


lib/CMakeFiles/lmbspecialops.dir/build.make:119: recipe for target 'lib/CMakeFiles/lmbspecialops.dir/lmbspecialops_generated_warp2d_cuda.cu.o' failed
make[2]: *** [lib/CMakeFiles/lmbspecialops.dir/lmbspecialops_generated_warp2d_cuda.cu.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'lib/CMakeFiles/lmbspecialops.dir/all' failed
make[1]: *** [lib/CMakeFiles/lmbspecialops.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

I have Cuda 10.0 installed because Cuda 8 didn't want to install under Ubuntu 18.04. Also because of that I use Tensorflow 1.14.0

**Comment by manymuch** [comment]
try this:
```export CPATH=$CPATH"/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/"```  
if you are using python3.5

from [here](https://github.com/NVIDIA/DALI/issues/99)

**Comment by Vaishnavi-1712** [comment]
Did you solve this error... I am also facing the same issue after cloning the same files

**Comment by MrMinemeet** [comment]
> Did you solve this error... I am also facing the same issue after cloning the same files

Sorry for the bit late reply.
Unfortunately I don't remember anymore and as stupid as I was back then I didn't write it down.
I only remember that I didn't get DeepTAM to work anyway because of too many compatibility issues and thus stopped trying it.
