### ISSUE TITLE
Tracking code with given weights give very high RMSE

### ISSUE THREAD

**Issue by stillbreeze** [lmb-freiburg/deeptam#4]
Hi,

I tried running the tracking code (`deeptam/tracking/examples/example_advanced_sequence.py`) but the translational RMSE printed at the end is 679702 m/s. The visualization shows no current image. The weights are loading fine. Any idea what might be going wrong? Here's the output for one of the intermediate frames. Also, every time I run it, there is a slight variation in the RMSE values. Shouldn't it remain the same since we are loading the pre trained weights. Thanks for the help in advance!

![track_res_167](https://user-images.githubusercontent.com/12224087/56100587-9531c000-5ee8-11e9-85ae-58549dbd41f0.png)

![image](https://user-images.githubusercontent.com/12224087/56100593-b2ff2500-5ee8-11e9-8baf-da9ffd5b3903.png)

**Comment by JingyuChan** [comment]
@stillbreeze I have met the same problem and I just fixed it. A possible solution is to change the skimage version to 0.14.2 if your skimage version is higher than 0.15.0. Hope that can help you a little bit.

**Comment by stillbreeze** [comment]
Thanks @JingyuChan ! It works fine now.

**Comment by zhz218** [comment]
I fixed the problems in the latest commit. Now it should also work with scikit-image 0.15.x. Thanks for pointing this out.
